config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
    path: :gurus,
    path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: :sessions, registrations: :registrations }

  resources :tests, only: :index do
    post 'start', on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :finish
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
      patch :update_inline, on: :member
    end
    resources :gists, only: %i[index]
    resources :badges
    get '/rule_values', to: 'rules#values'
  end

  resources :feedbacks, only: %i[new create]
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true

  def self.emails
    Admin.all.pluck(:email)
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_max_number, on: :create

  private

  def validate_max_number
    errors.add(:count_answers, "the number of answers should be < 4") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_one :rule, dependent: :destroy
  has_and_belongs_to_many :users
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :delete_all
  has_many :gists

  validates :body, presence: true

  def position
    test.questions.order(:id).pluck(:id).index(id) + 1
  end
end

app/models/rule.rb
class Rule < ApplicationRecord
  TYPES = %i[level category score attempts].freeze

  belongs_to :badge

  def self.values_by_type(type)
    send "#{type}_values"
  end

  def self.level_values
    Test.all.pluck(:level).uniq.map { |level| [level, level] }
  end

  def self.category_values
    Category.all.map { |category| [category.id, category.title] }
  end

  def self.attempts_values
    [[1, 1], [3, 3], [5, 5]]
  end

  def self.score_values
    [[75, 75], [90, 90], [100, 100]]
  end

  def text
    "#{I18n.t(attr, scope: 'admin.rules')}: #{value}"
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :questions, dependent: :delete_all
  has_many :test_passages, dependent: :delete_all
  has_many :users, through: :test_passages

  scope :easy, -> { where(level: [0..1]) }
  scope :medium, -> { where(level: [2..4]) }
  scope :difficult, -> { where('level > ?', 4) }
  scope :by_level, ->(level) { where(level: level) }
  scope :by_category, (lambda do |title|
                         joins(:category)
                           .where(categories: { title: title })
                           .order(title: :desc)
                           .pluck(:title)
                       end)
  scope :by_category_id, ->(category) { where(category: category)}
  scope :valid, -> { joins(questions: :answers).group(:id) }

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :time, numericality: { only_integer: true,
                                   greater_than_or_equal_to: 1 }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASSING_SCORE = 75

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, on: [:create, :update]

  scope :passed, -> { where(passed: true) }

  def accept!(answer_ids)
    self.correct_questions += 1 if answer_ids && correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def successful?
    score >= PASSING_SCORE
  end

  def first_attempt?
  user
    .completed_tests
    .where(tests: { id: test.id })
    .count
    .equal?(1)
  end

  def score
    @score ||= (correct_questions * 100.0 / test.questions.count).ceil
  end

  def progress
    ((current_question.position - 1) * 100.0 / test.questions.count).round(1)
  end

  def time_left
   return if test.time.blank?

    created_at + test.time * 60 - Time.current
  end

  def out_of_time
    test.time && time_left <= 0
  end

  private

  def before_validation_set_question
    self.current_question = next_question
    self.passed = true if successful?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    return test.questions.first unless current_question

    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :created_tests, class_name: 'Test', foreign_key: :author_id
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :gists
  has_many :feedbacks
  has_and_belongs_to_many :badges

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def completed_tests
    tests.where(test_passages: { passed: true })
  end

  def admin?
    is_a?(Admin)
  end

  def name
    return 'User' unless first_name || last_name

    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      @badge.create_rule(
        attr: params[:badge][:rule_type],
        value: params[:badge][:rule_value])
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :rule_id)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
    @my_badges = current_user.badges
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  after_action :greet_user, only: :create

  def greet_user
    flash[:notice] = t '.hello', name: current_user.name
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: %i[start]

  def index
    @tests = Test.valid
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def gist_hash(gist)
    gist.url.split('/').last
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    DateTime.current.year
  end

  def github_link(author, repo)
    link_to repo, "https://github.com/#{author}/#{repo}", target: 'blank'
  end

  def flash_message
    flashes = []
    flash.each do |key, message|
      flashes.push content_tag :p, message, class: "flash #{key}"
    end
    flashes.join.html_safe
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_header(question)
    title = question.new_record? ? 'Создать' : 'Редактировать'
    "#{title} #{question.test.title} вопрос"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def minutes_format(time)
    format('%02d', (time / 60).floor)
end

  def seconds_format(time)
    format('%02d', time % 60)
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.title %></td>
  <td><%= image_tag badge.image, class: 'badge-img' %></td>
  <td><%= badge.rule&.text %></td>
  <td><%= link_to t(:edit), edit_admin_badge_path(badge) %></td>
  <td>
    <%= link_to t(:delete),
                admin_badge_path(badge),
                'data-confirm': t(:confirm),
                'data-method': :delete %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class='row'>
  <div class='col col-md-6'>
    <%= form_with model: [:admin, @badge], local: true do |form| %>
      <div class='form-group'>
        <%= render 'shared/errors', resource: @badge %>
        <p class='mb-4'>
          <%= form.label :title %><br>
          <%= form.text_field :title, class: 'form-control', required: true %>
        </p>
        <p class='mb-4'>
          <label class='d-block'><%= t 'admin.badges.image' %></label>
          <% images = [['badge1.svg'] ,['badge2.svg'], ['badge3.svg']] %>
          <%= form.collection_radio_buttons(:image, images, :first, :first, { checked: @badge.image || images.first }) do |b| %>
            <%= b.label(class: 'text-center mr-4') { image_tag(b.text, width: '80', class: 'd-block mb-2') + b.radio_button } %>
          <% end %>
        </p>
      </div>
      <fieldset class='form-group'>
        <legend><%= t 'admin.badges.rule' %></legend>
        <p>
          <%= form.label :rule_type %>
          <% types = Rule::TYPES.map { |type| [type, t(type, scope: %i[admin rules])] } %>
          <% selected = @badge.new_record? ? types.first[0] : @badge.rule.attr %>
          <%= form.collection_select :rule_type, types, :first, :last, { selected: selected }, { class: 'custom-select'} %>
        </p>
        <p>
          <%= form.label :rule_value %>
          <% values = Rule.values_by_type(Rule::TYPES.first) %>
          <% selected = @badge.new_record? ? values.first[0] : @badge.rule.value %>
          <%= form.collection_select :rule_value, values, :first, :last, { selected: selected }, { class: 'custom-select'} %>
        </p>
      </fieldset>
      <p><%= form.submit class: 'btn btn-primary' %></p>
    </div>
  </div>
<% end %>

app/views/admin/badges/edit.html.erb
<h1 class='mb-4'><%= t '.heading' %></h1>
<%= render 'form' %>

<%= link_to t(:back), admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1><%= t '.heading' %></h1>
<p><%= link_to t(:new), new_admin_badge_path %></p>

<table class="table">
  <tr>
    <th class="sort-by-title pointer">
      <%= t 'badges.title' %>
      <%= octicon 'arrow-up', class: 'text-success hide' %>
      <%= octicon 'arrow-down', class: 'text-success hide' %>
    </th>
    <th><%= t 'badges.image' %></th>
    <th><%= t 'badges.rule' %></th>
    <th colspan='2'><%= t :actions %></th>
  </tr>
  <%= render @badges %>
</table>

app/views/admin/badges/new.html.erb
<h1 class='mb-4'><%= t '.heading' %></h1>
<%= render 'form' %>

<%= link_to t(:back), admin_badges_path %>

app/views/badges/_badge.html.erb
<% achieved = badge.in?(@my_badges) %>
<tr>
  <td>
    <%= badge.title %>
  </td>
  <td class="<%='opaque' unless achieved %>">
    <%= image_tag badge.image, class: 'badge-img' %>
  </td>
  <td>
    <%= check_box_tag :achieved, :achieved, achieved %>
  </td>
  <td>
    <%= @my_badges.group(:id).count[badge.id] %>
  </td>
</tr>

app/views/badges/index.html.erb
<div class='row'>
  <div class='col-md-6'>
    <h1 class='mb-4'><%= t '.heading' %></h1>
  </div>
  <div class='col-md-6 text-right'>
    <h2><%= @my_badges.count %></h2>
  </div>
</div>

<table class="table">
  <tr>
    <th class="sort-by-title pointer">
      <%= t 'badges.title' %>
      <%= octicon 'arrow-up', class: 'text-success hide' %>
      <%= octicon 'arrow-down', class: 'text-success hide' %>
    </th>
    <th><%= t 'badges.image' %></th>
    <th><%= t 'badges.achieved' %></th>
    <th><%= t 'badges.number' %></th>
  </tr>
  <%= render @badges %>
</table>