config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
    path: :gurus,
    path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: :sessions, registrations: :registrations }

  resources :tests, only: :index do
    post 'start', on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :finish
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
      patch :update_inline, on: :member
    end
    resources :gists, only: %i[index]
    resources :badges
    get '/rule_values', to: 'rules#values'
  end

  resources :feedbacks, only: %i[new create]
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true

  def self.emails
    Admin.all.pluck(:email)
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_max_number, on: :create

  private

  def validate_max_number
    errors.add(:count_answers, "the number of answers should be < 4") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_one :rule, dependent: :destroy
  has_and_belongs_to_many :users
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :delete_all
  has_many :gists

  validates :body, presence: true

  def position
    test.questions.order(:id).pluck(:id).index(id) + 1
  end
end

app/models/rule.rb
class Rule < ApplicationRecord
  TYPES = %i[level category score attempts].freeze

  belongs_to :badge

  def self.values_by_type(type)
    send "#{type}_values"
  end

  def self.level_values
    Test.all.pluck(:level).uniq.map { |level| [level, level] }
  end

  def self.category_values
    Category.all.map { |category| [category.id, category.title] }
  end

  def self.attempts_values
    [[1, 1], [3, 3], [5, 5]]
  end

  def self.score_values
    [[75, 75], [90, 90], [100, 100]]
  end

  def text
    "#{I18n.t(attr, scope: 'admin.rules')}: #{value}"
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :questions, dependent: :delete_all
  has_many :test_passages, dependent: :delete_all
  has_many :users, through: :test_passages

  scope :easy, -> { where(level: [0..1]) }
  scope :medium, -> { where(level: [2..4]) }
  scope :difficult, -> { where('level > ?', 4) }
  scope :by_level, ->(level) { where(level: level) }
  scope :by_category, (lambda do |title|
                         joins(:category)
                           .where(categories: { title: title })
                           .order(title: :desc)
                           .pluck(:title)
                       end)
  scope :by_category_id, ->(category) { where(category: category)}
  scope :valid, -> { joins(questions: :answers).group(:id) }

  validates :title, presence: true
  validates :title, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :time, numericality: { only_integer: true,
                                   greater_than_or_equal_to: 1 }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASSING_SCORE = 75

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, on: [:create, :update]

  scope :passed, -> { where(passed: true) }

  def accept!(answer_ids)
    self.correct_questions += 1 if answer_ids && correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def successful?
    score >= PASSING_SCORE
  end

  def first_attempt?
  user
    .completed_tests
    .where(tests: { id: test.id })
    .count
    .equal?(1)
  end

  def score
    @score ||= (correct_questions * 100.0 / test.questions.count).ceil
  end

  def progress
    ((current_question.position - 1) * 100.0 / test.questions.count).round(1)
  end

  def time_left
   return if test.time.blank?

    created_at + test.time * 60 - Time.current
  end

  def out_of_time
    test.time && time_left <= 0
  end

  private

  def before_validation_set_question
    self.current_question = next_question
    self.passed = true if successful?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    return test.questions.first unless current_question

    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :created_tests, class_name: 'Test', foreign_key: :author_id
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :gists
  has_many :feedbacks
  has_and_belongs_to_many :badges

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def completed_tests
    tests.where(test_passages: { passed: true })
  end

  def admin?
    is_a?(Admin)
  end

  def name
    return 'User' unless first_name || last_name

    "#{first_name} #{last_name}"
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: %i[start]

  def index
    @tests = Test.valid
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end
end

app/helpers/admin_helper.rb
module AdminHelper
  def gist_hash(gist)
    gist.url.split('/').last
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    DateTime.current.year
  end

  def github_link(author, repo)
    link_to repo, "https://github.com/#{author}/#{repo}", target: 'blank'
  end

  def flash_message
    flashes = []
    flash.each do |key, message|
      flashes.push content_tag :p, message, class: "flash #{key}"
    end
    flashes.join.html_safe
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_header(question)
    title = question.new_record? ? 'Создать' : 'Редактировать'
    "#{title} #{question.test.title} вопрос"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def minutes_format(time)
    format('%02d', (time / 60).floor)
end

  def seconds_format(time)
    format('%02d', time % 60)
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<nav class='navbar navbar-light bg-light'>
  <div class='container'>
    <div class='nav'>
      <%= link_to 'Test Guru', root_path, class: 'navbar-brand' %>
      <%= link_to 'Gists', admin_gists_path, class: 'btn btn-info' %>
      <%= link_to t('.tests'), admin_tests_path, class: 'nav-link' %>
      <%= link_to t('.badges'), admin_badges_path, class: 'nav-link' %>
</div>
<div class='nav'>
<span class='navbar-text'><%= t 'welcome_html', email: current_user.email %></span>
<%= link_to t(:log_out), destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <main class='main'>
      <div class='container'>
        <%= render 'shared/flash' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <main class='main'>
      <div class='container'>
        <%= render 'shared/flash' %>
        <%= yield %>
      </div>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, sanitize(message, attributes: %w(href target)), class: "alert alert-#{key.to_s == 'notice' ? 'success' : 'danger'}" %>
<% end %>

app/views/shared/_footer.html.erb
<footer style="border-top: 1px solid #ccc; margin-top: 100px; padding-top: 20px;">
  <div class='container'>
  <p>&copy; <%= current_year %> Морозов Александр</p>
  <p>
    <%= github_link('intokozo', 'TestGuru') %>
    &mdash; приложение для создания, редактирования и выполнения тестов.
  </p>
  <p>
    Учебный проект в онлайн-школе
    <%= link_to  'Thinknetica', 'https://thinknetica.com', target: 'blank' %>
  </p>
  <p>
    <%= link_to 'Обратная связь', new_feedback_path %>
  </p>
  </div>

</footer>

app/views/shared/_nav.html.erb
<nav class='navbar navbar-light bg-light'>
  <div class='container'>
    <div class='nav'>
      <%= link_to 'Test Guru', root_path, class: 'navbar-brand' %>
      <% if current_user.present? && current_user.admin? %>
          <%= link_to 'Admin panel', admin_tests_path, class: 'btn btn-info' %>
      <% end %>
            <%= link_to t('.my_badges'), badges_path, class: 'nav-link' %>
    </div>
  <div class='nav'>
    <% if user_signed_in? %>
      <span class='navbar-text'><%= t 'welcome_html', email: current_user.email %></span>
      <%= link_to t(:log_out), destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
    <% else %>
      <%= link_to t(:sign_up), new_user_registration_path, class: 'nav-item nav-link' %>
      <%= link_to t(:log_in), new_user_session_path, class: 'nav-item nav-link' %>
    <% end %>
  </div>
</div>
</nav>