config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
    path: :gurus,
    path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: :sessions, registrations: :registrations }

  resources :tests, only: :index do
    post 'start', on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :finish
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
      patch :update_inline, on: :member
    end
    resources :gists, only: %i[index]
    resources :badges
    get '/rule_values', to: 'rules#values'
  end

  resources :feedbacks, only: %i[new create]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :delete_all
  has_many :gists

  validates :body, presence: true

  def position
    test.questions.order(:id).pluck(:id).index(id) + 1
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  PASSING_SCORE = 75

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, on: [:create, :update]

  scope :passed, -> { where(passed: true) }

  def accept!(answer_ids)
    self.correct_questions += 1 if answer_ids && correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def successful?
    score >= PASSING_SCORE
  end

  def first_attempt?
  user
    .completed_tests
    .where(tests: { id: test.id })
    .count
    .equal?(1)
  end

  def score
    @score ||= (correct_questions * 100.0 / test.questions.count).ceil
  end

  def progress
    ((current_question.position - 1) * 100.0 / test.questions.count).round(1)
  end

  def time_left
   return if test.time.blank?

    created_at + test.time * 60 - Time.current
  end

  def out_of_time
    test.time && time_left <= 0
  end

  private

  def before_validation_set_question
    self.current_question = next_question
    self.passed = true if successful?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    return test.questions.first unless current_question

    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :set_test_passage

  def show; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || @test_passage.out_of_time
      finish_test
    else
      render :show
    end
  end

  def result; end

  def gist
    gist_service = GistQuestionService.new(@test_passage.current_question)
    response = gist_service.call

    if gist_service.success?
      current_user.gists.create(question_id: @test_passage.current_question.id, url: response.html_url)
      flash_msg = { notice: view_context.link_to('Gist URL', response.html_url, target: :_blank) }
    else
      flash_msg = { alert: 'There was an error!' }
    end

    redirect_to @test_passage, flash_msg
  end

  def finish
    @test_passage.update(passed: true) if @test_passage.successful?

    finish_test
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def finish_test
    begin
      testsMailer.completed_test(@test_passage).deliver_now
    rescue Net::SMTPAuthenticationError
      flash_msg = { alert: 'Gmail authentication error' }
    end
    redirect_to result_test_passage_path(@test_passage), flash_msg || {}
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def minutes_format(time)
    format('%02d', (time / 60).floor)
end

  def seconds_format(time)
    format('%02d', time % 60)
  end
end

app/views/test_passages/_form.html.erb
<%= form_with(model: test_passage, local: true) do |form| %>
  <% if test_passage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_passage.errors.count, "error") %> prohibited this test_passage from being saved:</h2>

      <ul>
      <% test_passage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/test_passages/edit.html.erb
<h1>Editing Test Passage</h1>

<%= render 'form', test_passage: @test_passage %>

<%= link_to 'Show', @test_passage %> |
<%= link_to 'Back', test_passages_path %>

app/views/test_passages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Passages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_passages.each do |test_passage| %>
      <tr>
        <td><%= link_to 'Show', test_passage %></td>
        <td><%= link_to 'Edit', edit_test_passage_path(test_passage) %></td>
        <td><%= link_to 'Destroy', test_passage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Passage', new_test_passage_path %>

app/views/test_passages/new.html.erb
<h1>New Test Passage</h1>

<%= render 'form', test_passage: @test_passage %>

<%= link_to 'Back', test_passages_path %>

app/views/test_passages/result.html.erb
<h2><%= t '.title', name: @test_passage.test.title %></h2>
<hr>
<% successful = @test_passage.successful? %>
<p>
    <%= t '.score' %>
  <span class="text-<%= successful ? 'success' : 'danger' %>">
    <%= number_to_percentage(@test_passage.score, precision: 0) %>
  </span>
</p>

<p class="test__message">
  <%= successful ? t('.success') : t('.failure') %>
</p>

<%= link_to t('back'), tests_path, class: 'btn btn-link' %>

app/views/test_passages/show.html.erb
<div class='row'>
  <div class='col-md-6'>
    <h1 class='mb-4'><%= t '.title', name: @test_passage.test.title %></h1>
  </div>
  <% if @test_passage.test.time %>
    <div class='col-md-6 text-right'>
      <div class='timer text-success'>
        <span class='timer-min'><%= minutes_format @test_passage.time_left %></span>
        <span>:</span>
        <span class='timer-sec'><%= seconds_format @test_passage.time_left %></span>
      </div>
    </div>
  <% end %>
</div>
<div class='card'>
  <div class='card-header'>
    <div class='mb-2'>
      <%= t '.question_html', position: @test_passage.current_question.position, total: @test_passage.test.questions.count %>
    </div>
        <div class='progress mb-1'>
          <div
            class='progress-bar bg-success'
            role='progressbar'
            style='width: <%= @test_passage.progress %>%'
            aria-valuenow='<%= @test_passage.progress %>'
            aria-valuemin='0'
            aria-valuemax='100'>
              <%= @test_passage.progress %>%
          </div>
        </div>
  </div>
  <div class='card-body'>
    <h4 class='card-title mb-4'>
      <%= @test_passage.current_question.body %>
    </h4>
    <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
          <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
            <div class='form-group'>
              <%= b.label  do %>
                <%= b.check_box %>
                <%= b.object.body %>
              <% end %>
            </div>
      <% end %>
      <p><%= link_to t('.gist_question'), gist_test_passage_path(@test_passage), method: :post %></p>
      <%= form.submit t('.next'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>