config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users,
    path: :gurus,
    path_names: { sign_in: :login, sign_out: :logout },
    controllers: { sessions: :sessions, registrations: :registrations }

  resources :tests, only: :index do
    post 'start', on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :finish
      post :gist
    end
  end

  resources :badges, only: :index

  namespace :admin do
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
      patch :update_inline, on: :member
    end
    resources :gists, only: %i[index]
    resources :badges
    get '/rule_values', to: 'rules#values'
  end

  resources :feedbacks, only: %i[new create]
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :delete_all
  has_many :gists

  validates :body, presence: true

  def position
    test.questions.order(:id).pluck(:id).index(id) + 1
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :set_question, except: %i[index new create]
  before_action :set_test, only: %i[index new create]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render html: '<b>Record was not found!</b>'.html_safe, status: 404
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_header(question)
    title = question.new_record? ? 'Создать' : 'Редактировать'
    "#{title} #{question.test.title} вопрос"
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <h2><%= form_header @question %></h2>
  <%= render 'shared/errors', resource: @question %>
  <div>
    <div><%= form.label :body, 'Question' %></div>
    <%= form.text_area :body, rows: 5, cols: 50 %>
  </div>
  <%= form.submit 'Save' %>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t(:show), admin_question_path(question) %></td>
  <td><%= link_to t(:edit), edit_admin_question_path(question) %></td>
  <td>
    <%= link_to t(:delete),
                admin_question_path(question),
                'data-confirm': t(:confirm),
                'data-method': :delete %>
  </td>
</tr>

app/views/admin/questions/_questoin.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to 'show', admin_question_path(question) %></td>
  <td><%= link_to 'edit', edit_admin_question_path(question) %></td>
  <td>
    <%= link_to 'delete',
                admin_question_path(question),
                'data-confirm': 'Are you sure?',
                'data-method': :delete %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test) %>

app/views/admin/questions/show.html.erb
<p><%= link_to 'all questions', admin_test_path(@question.test) %></p>
<h1><%= @question.test.title %> question</h1>
<p><%= @question.body %></p>

<h2>Answers</h2>
<%= link_to 'New answer', new_admin_question_answer_path(@question) %>
<ol>
  <%= render @question.answers %>
</ol>

<p>
  <%= link_to 'edit', edit_admin_question_path(@question) %>
  <%= link_to 'delete',
              admin_question_path(@question),
              'data-confirm': 'Are you sure?',
              'data-method': :delete %>
</p>